### ISSUE TITLE
getting 'Cannot add or update a child row' error while importing dump file in phpMyAdmin

### ISSUE THREAD

**Issue by arshadalisoomro** [muhammadtarek/smug-reservation-system#1]
Assalam-u-Alekum!

I searched the github and found this repository intresting, saw screen shots @ [SMUG-Reservation-System](https://www.behance.net/gallery/37635393/SMUG-Reservation-System), I forked project and got 

![smug](https://cloud.githubusercontent.com/assets/2489546/15803531/f7954056-2afb-11e6-9c08-ee471987a3d0.PNG)

while importing DATABASE.sql file using phpMyAdmin.

Any solution to that Please?

Regards:
Arshad Ali Soomro

**Comment by muhammadtarek** [comment]
W Alekum Assalam

hi, Arshad Ali Soomro. Thanks for reporting that, sorry for replying late.
we will search for a fix for this issue, and I will contact you as soon as it fixed

Regards,
Muhammad Tarek

**Comment by muhammadtarek** [comment]
Hi, Arshad Ali Soomro

The problem was that feedback table has some records that are connected with user_id, when I exported the database I cleared the users table because it contains some personal information. This file has empty feedback so this error won't show up.

I have uploaded the new DATABASE.sql file. You can try it now

Sorry again for replying late

Regards,
Muhammad Tarek
